baseURL = 'https://blog.norin.me/'
locale = 'zh-CN'
title = 'Nor Blog'

[params]
  description = '学习、研究与成长记录。'
  author = 'norin'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.highlight]
    noClasses = false
    codeFences = true

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '专栏'
    url = '/#series'
    weight = 2
